server:
  port: 8080

security:
  basic:
    enabled: false

entitymanager:
  packagesToScan: com.hrapp.*


#Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/hrworkapp?useUnicode=true&characterEncoding=UTF-8&&useSSL=false
  username: root
  password: 6577
  

#Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update
     